language: python
python:
  - "3.5"
services:
  - docker
env:
  global:
    - GOOS=linux
    - GOARCH=amd64
    - PROJECT_NAME=scene-detector

before_install:
  - ECR_HELPERS_PATH=https://s3.amazonaws.com/ops-yotpo/public/docker/ecr-login-helper
  - mkdir -p $HOME/bin
  - export PATH=$PATH:$HOME/bin
  - curl -L $ECR_HELPERS_PATH/docker-credential-ecr-login -o $HOME/bin/docker-credential-ecr-login
  - chmod +x $HOME/bin/docker-credential-ecr-login
  - mkdir -p $HOME/.docker/
  - curl -L $ECR_HELPERS_PATH/config.json -o $HOME/.docker/config.json
  - docker images ${CONTAINER_REGISTRY_HOST}/${PROJECT}

jobs:
  include:
    - stage: build
      script:
        - docker build -t 402837048690.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME} --cache-from 402837048690.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME} -f Dockerfile .
        - docker tag 402837048690.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME} 402837048690.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME}:${TRAVIS_COMMIT}
        - docker push 402837048690.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME}:${TRAVIS_COMMIT}
        - docker tag 402837048690.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME} 402837048690.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME}:${TRAVIS_BRANCH}
        - docker push 402837048690.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME}:${TRAVIS_BRANCH}
    - stage: deploy
      if: branch = master
      script:
        - docker tag 402837048690.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME} 402837048690.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME}:master
        - docker tag 402837048690.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME} 402837048690.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME}:latest
        - docker push 402837048690.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME}:master 402837048690.dkr.ecr.us-east-1.amazonaws.com/${PROJECT_NAME}:latest